### ISSUE TITLE
Bug: Errors when footnote in citation/当在引用中添加脚注时报错

### ISSUE THREAD

**Issue by Quasimoodo** [kchen0x/hexo-reference#21]
在我在引用之中添加脚注，会在生成时报错：

> INFO  Start processing
FATAL {
  err: TypeError: Cannot read properties of undefined (reading 'content')
      at D:\Code\Quasimoodo.github.io\node_modules\hexo-reference\src\footnotes.js:55:43
      at String.replace (<anonymous>)
      at renderFootnotes (D:\Code\Quasimoodo.github.io\node_modules\hexo-reference\src\footnotes.js:53:17)
      at Hexo.<anonymous> (D:\Code\Quasimoodo.github.io\node_modules\hexo-reference\index.js:6:18)
      at Hexo.tryCatcher (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\method.js:15:34)
      at D:\Code\Quasimoodo.github.io\node_modules\hexo\lib\extend\filter.js:67:52
      at tryCatcher (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\util.js:16:23)
      at Object.gotValue (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\reduce.js:166:18)
      at Object.gotAccum (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\reduce.js:155:25)
      at Object.tryCatcher (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\async.js:102:5)
      at Async.drainQueues [as _onImmediate] (D:\Code\Quasimoodo.github.io\node_modules\bluebird\js\release\async.js:15:14)
      at process.processImmediate (node:internal/timers:471:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html

复现代码如图，在typora中可以正常渲染：
<img width="543" alt="image" src="https://user-images.githubusercontent.com/63183315/174592415-6ed6c068-de60-4825-97e9-314a24e4e1d6.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/63183315/174592464-aad76b79-4e2d-426d-871a-6fae5c4e3866.png">

**Comment by Falas-Mithlond** [comment]
请问这个问题后面解决了吗

**Comment by Quasimoodo** [comment]
> 请问这个问题后面解决了吗

我很久没用了 当时的印象是解决了 换了个包 你再找找 应该有现成的经验

**Comment by kchen0x** [comment]
Fixed in https://github.com/kchen0x/hexo-reference/commit/cb98a27. The parser no longer dereferences missing footnote content and preserves undefined references instead of throwing or deleting them. Blockquote/quotation content with footnote markers was also verified during the regression pass.
